---
- name: Create mysql database
  mysql_db: 
    name: "{{ wp_mysql_db }}" 
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: "T01 A. --> {{ ansible_distribution_file_variety }}: Create mysql user"
  mysql_user:
    login_user: debian-sys-maint 
    login_password: AzCaYWD8BNHlkFls
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}"
    priv: '*.*:ALL'
  when: ansible_distribution_file_variety == "Debian"

- name: "T01 B. --> {{ ansible_distribution_file_variety }}: Create mysql user"
  mysql_user:
    login_user: root
    login_password: Sk,g)&_i6(hK
    name: "{{ wp_mysql_user }}"
    password: "{{ wp_mysql_password }}"
    priv: '*.*:ALL'
  when: ansible_distribution_file_variety == "RedHat"
  
 
