---
- name: Download WordPress  
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress  
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no

- name: Update default Apache site
  lineinfile:
    path: /etc/apache2/sites-enabled/000-default.conf
    regexp: "(.)+DocumentRoot /var/www/html"
    line: "DocumentRoot /var/www/wordpress"

- name: "{{ ansible_distribution_file_variety }}: restart apache"
  service: name=apache2 state=restarted
  when: ansible_distribution_file_variety == "Debian"


- name: "{{ ansible_distribution_file_variety }}: restart apache"
  service: name=httpd state=restarted
  when: ansible_distribution_file_variety == "RedHat"

- name: Copy sample config file
  command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php 
  args:
    creates: /var/www/wordpress/wp-config.php

- name: Update WordPress config file
  lineinfile:
    path: /var/www/wordpress/wp-config.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}

      
